TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/A34970aSup/devA34970a.db
DB_INSTALLS += $(TOP)/A34970aSup/devA34970a.proto

#=======================================
include $(TOP)/configure/RULES
